project:
  type: website
  output-dir: docs

website:
  title: "Reproducible data analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: appendix.qmd
        text: Appendix

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true