---
title: "Reproducible Data Analysis"
toc: false
---

The ability to **analyze data using code** is increasingly in demand across academic disciplines from sciences to the humanities, as well as industry.

Using code instead of point-and-click software means that analyses can be **reproducible**, which allows them to be **re-used** and **trusted**.

In this course, students will learn how to use the **R programming language** among other tools for **reproducible data analysis**. Emphasis will be placed on practical usage and best practices to ensure reproducibility. No prior programming experience is required, but it will be helpful if students have a topic that they are interested in analyzing for the final report. All students are expected to have access to a modern computer (laptop) capable of installing and running [R](https://cran.rstudio.com/), [RStudio](https://posit.co/download/rstudio-desktop/), [Git](https://git-scm.com/), and [Quarto](https://quarto.org/).

## Goals

The goal of this course is to **learn how to conduct reproducible data analysis using R**.

By the end of the course, students should be able to:

  - Load, clean, and visualize data using R
  - Track changes to code using Git and GitHub
  - Write a reproducible report using Quarto

## Slides

- [Day 1 (2025-06-12): Introduction: Why code? Why reproducibility?](day1/index.qmd)

- [Day 2 (2025-06-19): Git and GitHub](day2/index.qmd)

- [Day 3 (2025-06-26): Basic usage of R and RStudio](day3/index.qmd)

- [Day 4 (2025-07-03): Data loading and tidying with tidyverse](day4/index.qmd)

- [Day 5 (Media Day): Joining data](day5/index.qmd)

- [Day 6 (2025-07-10): Data visualization with ggplot2](day6/index.qmd)

- [Day 7 (2025-07-17): Writing documents with Quarto](day7/index.qmd)

- [Day 8 (2025-07-24): Quarto, part II](day8/index.qmd)

## Recordings

- [Day 5: Joining data](https://youtu.be/NOfTnoEtCYk)

For other lecture recordings, see Moodle.

## Materials

- [Day 2: Git and GitHub](day2/day02_intro_to_git.qmd)

- [Day 3: R and RStudio](day3/day03_intro_to_r.qmd)

- [Day 4: Data loading and tidying](day4/day04_tidy.qmd)

- [Day 5: Joining data (R for Data Science)](https://r4ds.hadley.nz/joins)

- [Day 6: ggplot2](day6/day06_ggplot2.qmd)

- [Day 7: Introduction to Reproducible Publications with Quarto (The Carpentries Lesson)](https://carpentries-incubator.github.io/reproducible-publications-quarto/)

- [Final Report Example](https://github.com/data-analysis-chiba/gapminder-report/)

## Important Deadlines

- 2025-06-25 11:59PM: [Day 2 homework](https://github.com/data-analysis-chiba/day02-git/blob/main/git_facts.md) due

- 2025-07-02 11:59PM: [Day 3 homework](https://github.com/data-analysis-chiba/day03-r/blob/main/day03_homework.R) due

- 2025-07-09 11:59PM: [Day 4 homework](https://github.com/data-analysis-chiba/day04-tidy/blob/main/day04_homework.R) due

- 2025-07-16 11:59PM: [Day 5 homework](https://github.com/data-analysis-chiba/day05-join/blob/main/day05_homework.R) due

- 2025-07-30 11:59PM: Final paper due

## About homework sets

All homework assignments (except Day 2) are submitted as R scripts.

Your code must **run without errors**.

The easiest way to check this is to restart RStudio by closing and opening it, then opening the R script and pressing the "Source" button.
Your code should run without errors, and any expected objects such as `answer_1`, etc. should show up in the environment panel.

The process for the final paper is similar, but instead of clicking "Source", click "Render".

Please check this before submitting your assignments!

## Extra Practice

The following are interactive tutorials in Japanese that you can run in your web browser. They were designed for the [情報処理演習 course](https://joelnitta.github.io/joho-shori/). Note that although the tutorials are used as homework in the 情報処理演習 course, **they are NOT required assignments for this course**. I only provide them here so you can use them for extra practice if you want. Please note that bandwidth is limited to run the tutorials, so they may not always be available.

以下のリンクは元々は[「情報処理演習」](https://joelnitta.github.io/joho-shori/)のために作成された、webブラウザの中で実行できるRコードのチュートリアルです。

注意：以下のチュートリアルは「情報処理演習」の宿題に使われていますが、**本授業の宿題ではありません。** 復習のためだけに掲載されています。

なお、使用量に限りがありますので、同時に数人以上使われている場合は接続できない可能性があります。

1. [チュートリアルについて](https://joelnitta.shinyapps.io/00-learnr/)
2. [R入門](https://joelnitta.shinyapps.io/01-intro/)
3. [ベクトルについて](https://joelnitta.shinyapps.io/02-vectors)
4. [データをファイルから読み込む](https://joelnitta.shinyapps.io/03-load/)
5. [データの整理（1）](https://joelnitta.shinyapps.io/04-tidy-1/)
6. [データの整理（2）](https://joelnitta.shinyapps.io/05-tidy-2/)
7. [データの可視化（1）](https://joelnitta.shinyapps.io/06-plot-1/)
8. [データの可視化（2）](https://joelnitta.shinyapps.io/07-plot-2/)

## Office Hours

By appointment, please send an email to <joelnitta@chiba-u.jp>

## Syllabus

[Syllabus in English](https://syllabus.gs.chiba-u.jp/2025/101101101076000/Z011531301/en_US)
